// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTxsdoNxiuxpVwT4n04DfDk2DlZkqKOoM',
    appId: '1:419013838402:web:d0b852bfb396d3d24e4fdb',
    messagingSenderId: '419013838402',
    projectId: 'find-stuff-2131a',
    authDomain: 'find-stuff-2131a.firebaseapp.com',
    storageBucket: 'find-stuff-2131a.firebasestorage.app',
    measurementId: 'G-E9RS149YYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNVAcURqBFYt0s5LwMOOfdLkRc4nqJzlc',
    appId: '1:419013838402:android:286d53c0b74178da4e4fdb',
    messagingSenderId: '419013838402',
    projectId: 'find-stuff-2131a',
    storageBucket: 'find-stuff-2131a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRnnHcI_TRlKAID7QVponYdwhFd8WEIQI',
    appId: '1:419013838402:ios:e2d8aa8c981956d84e4fdb',
    messagingSenderId: '419013838402',
    projectId: 'find-stuff-2131a',
    storageBucket: 'find-stuff-2131a.firebasestorage.app',
    iosBundleId: 'com.example.findStuff',
  );
}
