name: Flutter Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: stable

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze code (without failing on infos or warnings)
      - name: Analyze project source
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      # Run tests (if any)
      - name: Run tests
        run: flutter test

      # Build Android APK only
      - name: Build Android APK
        run: flutter build apk --release
